### ISSUE TITLE
Bazel uses protoc 3.19.6 for proto_library

### ISSUE THREAD

**Issue by mkruskal-google** [bazelbuild/rules_proto#197]
I'm trying to enable Bazel 7 in our CI for https://github.com/protocolbuffers/protobuf, and it seems like something has changed in Bazel so that `proto_library` uses 3.19.6 even in our repo (see [failure](https://github.com/protocolbuffers/protobuf/actions/runs/7201398568/job/19617441255?pr=15078)).  I suspect this has to do with the proto_lang_toolchain changes, where our old overrides to use the workspace protoc don't work anymore.  It looks like this has been replaced with proto_toolchain, but AFAICT this rule hasn't actually been released yet by rules_proto.

What can we do here?

**Comment by comius** [comment]
I believe this was resolved and was due to CI setup.

**Comment by andrewkatson** [comment]
I am still getting this issue on https://github.com/protocolbuffers/protobuf/issues/15711 

@comius how did you fix it?
